### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by SamihElsakhawi** [Kidel/DynamicResolution-for-Unity3D#1]
Hey, thanks for sharing your asset!

But how do i implement it on my game? do i need to attach DynamicResolution.cs on the camera? a GameObject? or a Canvas?

Thanks a lot!

Regards, Sam.

**Comment by Kidel** [comment]
You're welcome. You need to add it to a Text object in a Canvas. It will also display stats if you set the corresponding variable.
